answer_paths:
  cases/eval_0-0-0.yaml:
  - answer_0-0-0_try_0.txt
  - answer_0-0-0_try_1.txt
  - answer_0-0-0_try_2.txt
  cases/eval_0-0-1.yaml:
  - answer_0-0-1_try_0.txt
  - answer_0-0-1_try_1.txt
  - answer_0-0-1_try_2.txt
  cases/eval_0-0-10.yaml:
  - answer_0-0-10_try_0.txt
  - answer_0-0-10_try_1.txt
  - answer_0-0-10_try_2.txt
  cases/eval_0-0-100.yaml:
  - answer_0-0-100_try_0.txt
  - answer_0-0-100_try_1.txt
  - answer_0-0-100_try_2.txt
  cases/eval_0-0-101.yaml:
  - answer_0-0-101_try_0.txt
  - answer_0-0-101_try_1.txt
  - answer_0-0-101_try_2.txt
  cases/eval_0-0-102.yaml:
  - answer_0-0-102_try_0.txt
  - answer_0-0-102_try_1.txt
  - answer_0-0-102_try_2.txt
  cases/eval_0-0-103.yaml:
  - answer_0-0-103_try_0.txt
  - answer_0-0-103_try_1.txt
  - answer_0-0-103_try_2.txt
  cases/eval_0-0-104.yaml:
  - answer_0-0-104_try_0.txt
  - answer_0-0-104_try_1.txt
  - answer_0-0-104_try_2.txt
  cases/eval_0-0-105.yaml:
  - answer_0-0-105_try_0.txt
  - answer_0-0-105_try_1.txt
  - answer_0-0-105_try_2.txt
  cases/eval_0-0-106.yaml:
  - answer_0-0-106_try_0.txt
  - answer_0-0-106_try_1.txt
  - answer_0-0-106_try_2.txt
  cases/eval_0-0-107.yaml:
  - answer_0-0-107_try_0.txt
  - answer_0-0-107_try_1.txt
  - answer_0-0-107_try_2.txt
  cases/eval_0-0-108.yaml:
  - answer_0-0-108_try_0.txt
  - answer_0-0-108_try_1.txt
  - answer_0-0-108_try_2.txt
  cases/eval_0-0-109.yaml:
  - answer_0-0-109_try_0.txt
  - answer_0-0-109_try_1.txt
  - answer_0-0-109_try_2.txt
  cases/eval_0-0-11.yaml:
  - answer_0-0-11_try_0.txt
  - answer_0-0-11_try_1.txt
  - answer_0-0-11_try_2.txt
  cases/eval_0-0-110.yaml:
  - answer_0-0-110_try_0.txt
  - answer_0-0-110_try_1.txt
  - answer_0-0-110_try_2.txt
  cases/eval_0-0-111.yaml:
  - answer_0-0-111_try_0.txt
  - answer_0-0-111_try_1.txt
  - answer_0-0-111_try_2.txt
  cases/eval_0-0-112.yaml:
  - answer_0-0-112_try_0.txt
  - answer_0-0-112_try_1.txt
  - answer_0-0-112_try_2.txt
  cases/eval_0-0-113.yaml:
  - answer_0-0-113_try_0.txt
  - answer_0-0-113_try_1.txt
  - answer_0-0-113_try_2.txt
  cases/eval_0-0-114.yaml:
  - answer_0-0-114_try_0.txt
  - answer_0-0-114_try_1.txt
  - answer_0-0-114_try_2.txt
  cases/eval_0-0-115.yaml:
  - answer_0-0-115_try_0.txt
  - answer_0-0-115_try_1.txt
  - answer_0-0-115_try_2.txt
  cases/eval_0-0-116.yaml:
  - answer_0-0-116_try_0.txt
  - answer_0-0-116_try_1.txt
  - answer_0-0-116_try_2.txt
  cases/eval_0-0-117.yaml:
  - answer_0-0-117_try_0.txt
  - answer_0-0-117_try_1.txt
  - answer_0-0-117_try_2.txt
  cases/eval_0-0-118.yaml:
  - answer_0-0-118_try_0.txt
  - answer_0-0-118_try_1.txt
  - answer_0-0-118_try_2.txt
  cases/eval_0-0-119.yaml:
  - answer_0-0-119_try_0.txt
  - answer_0-0-119_try_1.txt
  - answer_0-0-119_try_2.txt
  cases/eval_0-0-12.yaml:
  - answer_0-0-12_try_0.txt
  - answer_0-0-12_try_1.txt
  - answer_0-0-12_try_2.txt
  cases/eval_0-0-120.yaml:
  - answer_0-0-120_try_0.txt
  - answer_0-0-120_try_1.txt
  - answer_0-0-120_try_2.txt
  cases/eval_0-0-121.yaml:
  - answer_0-0-121_try_0.txt
  - answer_0-0-121_try_1.txt
  - answer_0-0-121_try_2.txt
  cases/eval_0-0-122.yaml:
  - answer_0-0-122_try_0.txt
  - answer_0-0-122_try_1.txt
  - answer_0-0-122_try_2.txt
  cases/eval_0-0-123.yaml:
  - answer_0-0-123_try_0.txt
  - answer_0-0-123_try_1.txt
  - answer_0-0-123_try_2.txt
  cases/eval_0-0-124.yaml:
  - answer_0-0-124_try_0.txt
  - answer_0-0-124_try_1.txt
  - answer_0-0-124_try_2.txt
  cases/eval_0-0-125.yaml:
  - answer_0-0-125_try_0.txt
  - answer_0-0-125_try_1.txt
  - answer_0-0-125_try_2.txt
  cases/eval_0-0-126.yaml:
  - answer_0-0-126_try_0.txt
  - answer_0-0-126_try_1.txt
  - answer_0-0-126_try_2.txt
  cases/eval_0-0-127.yaml:
  - answer_0-0-127_try_0.txt
  - answer_0-0-127_try_1.txt
  - answer_0-0-127_try_2.txt
  cases/eval_0-0-128.yaml:
  - answer_0-0-128_try_0.txt
  - answer_0-0-128_try_1.txt
  - answer_0-0-128_try_2.txt
  cases/eval_0-0-129.yaml:
  - answer_0-0-129_try_0.txt
  - answer_0-0-129_try_1.txt
  - answer_0-0-129_try_2.txt
  cases/eval_0-0-13.yaml:
  - answer_0-0-13_try_0.txt
  - answer_0-0-13_try_1.txt
  - answer_0-0-13_try_2.txt
  cases/eval_0-0-130.yaml:
  - answer_0-0-130_try_0.txt
  - answer_0-0-130_try_1.txt
  - answer_0-0-130_try_2.txt
  cases/eval_0-0-131.yaml:
  - answer_0-0-131_try_0.txt
  - answer_0-0-131_try_1.txt
  - answer_0-0-131_try_2.txt
  cases/eval_0-0-14.yaml:
  - answer_0-0-14_try_0.txt
  - answer_0-0-14_try_1.txt
  - answer_0-0-14_try_2.txt
  cases/eval_0-0-15.yaml:
  - answer_0-0-15_try_0.txt
  - answer_0-0-15_try_1.txt
  - answer_0-0-15_try_2.txt
  cases/eval_0-0-16.yaml:
  - answer_0-0-16_try_0.txt
  - answer_0-0-16_try_1.txt
  - answer_0-0-16_try_2.txt
  cases/eval_0-0-17.yaml:
  - answer_0-0-17_try_0.txt
  - answer_0-0-17_try_1.txt
  - answer_0-0-17_try_2.txt
  cases/eval_0-0-18.yaml:
  - answer_0-0-18_try_0.txt
  - answer_0-0-18_try_1.txt
  - answer_0-0-18_try_2.txt
  cases/eval_0-0-19.yaml:
  - answer_0-0-19_try_0.txt
  - answer_0-0-19_try_1.txt
  - answer_0-0-19_try_2.txt
  cases/eval_0-0-2.yaml:
  - answer_0-0-2_try_0.txt
  - answer_0-0-2_try_1.txt
  - answer_0-0-2_try_2.txt
  cases/eval_0-0-20.yaml:
  - answer_0-0-20_try_0.txt
  - answer_0-0-20_try_1.txt
  - answer_0-0-20_try_2.txt
  cases/eval_0-0-21.yaml:
  - answer_0-0-21_try_0.txt
  - answer_0-0-21_try_1.txt
  - answer_0-0-21_try_2.txt
  cases/eval_0-0-22.yaml:
  - answer_0-0-22_try_0.txt
  - answer_0-0-22_try_1.txt
  - answer_0-0-22_try_2.txt
  cases/eval_0-0-23.yaml:
  - answer_0-0-23_try_0.txt
  - answer_0-0-23_try_1.txt
  - answer_0-0-23_try_2.txt
  cases/eval_0-0-24.yaml:
  - answer_0-0-24_try_0.txt
  - answer_0-0-24_try_1.txt
  - answer_0-0-24_try_2.txt
  cases/eval_0-0-25.yaml:
  - answer_0-0-25_try_0.txt
  - answer_0-0-25_try_1.txt
  - answer_0-0-25_try_2.txt
  cases/eval_0-0-26.yaml:
  - answer_0-0-26_try_0.txt
  - answer_0-0-26_try_1.txt
  - answer_0-0-26_try_2.txt
  cases/eval_0-0-27.yaml:
  - answer_0-0-27_try_0.txt
  - answer_0-0-27_try_1.txt
  - answer_0-0-27_try_2.txt
  cases/eval_0-0-28.yaml:
  - answer_0-0-28_try_0.txt
  - answer_0-0-28_try_1.txt
  - answer_0-0-28_try_2.txt
  cases/eval_0-0-29.yaml:
  - answer_0-0-29_try_0.txt
  - answer_0-0-29_try_1.txt
  - answer_0-0-29_try_2.txt
  cases/eval_0-0-3.yaml:
  - answer_0-0-3_try_0.txt
  - answer_0-0-3_try_1.txt
  - answer_0-0-3_try_2.txt
  cases/eval_0-0-30.yaml:
  - answer_0-0-30_try_0.txt
  - answer_0-0-30_try_1.txt
  - answer_0-0-30_try_2.txt
  cases/eval_0-0-31.yaml:
  - answer_0-0-31_try_0.txt
  - answer_0-0-31_try_1.txt
  - answer_0-0-31_try_2.txt
  cases/eval_0-0-32.yaml:
  - answer_0-0-32_try_0.txt
  - answer_0-0-32_try_1.txt
  - answer_0-0-32_try_2.txt
  cases/eval_0-0-33.yaml:
  - answer_0-0-33_try_0.txt
  - answer_0-0-33_try_1.txt
  - answer_0-0-33_try_2.txt
  cases/eval_0-0-34.yaml:
  - answer_0-0-34_try_0.txt
  - answer_0-0-34_try_1.txt
  - answer_0-0-34_try_2.txt
  cases/eval_0-0-35.yaml:
  - answer_0-0-35_try_0.txt
  - answer_0-0-35_try_1.txt
  - answer_0-0-35_try_2.txt
  cases/eval_0-0-36.yaml:
  - answer_0-0-36_try_0.txt
  - answer_0-0-36_try_1.txt
  - answer_0-0-36_try_2.txt
  cases/eval_0-0-37.yaml:
  - answer_0-0-37_try_0.txt
  - answer_0-0-37_try_1.txt
  - answer_0-0-37_try_2.txt
  cases/eval_0-0-38.yaml:
  - answer_0-0-38_try_0.txt
  - answer_0-0-38_try_1.txt
  - answer_0-0-38_try_2.txt
  cases/eval_0-0-39.yaml:
  - answer_0-0-39_try_0.txt
  - answer_0-0-39_try_1.txt
  - answer_0-0-39_try_2.txt
  cases/eval_0-0-4.yaml:
  - answer_0-0-4_try_0.txt
  - answer_0-0-4_try_1.txt
  - answer_0-0-4_try_2.txt
  cases/eval_0-0-40.yaml:
  - answer_0-0-40_try_0.txt
  - answer_0-0-40_try_1.txt
  - answer_0-0-40_try_2.txt
  cases/eval_0-0-41.yaml:
  - answer_0-0-41_try_0.txt
  - answer_0-0-41_try_1.txt
  - answer_0-0-41_try_2.txt
  cases/eval_0-0-42.yaml:
  - answer_0-0-42_try_0.txt
  - answer_0-0-42_try_1.txt
  - answer_0-0-42_try_2.txt
  cases/eval_0-0-43.yaml:
  - answer_0-0-43_try_0.txt
  - answer_0-0-43_try_1.txt
  - answer_0-0-43_try_2.txt
  cases/eval_0-0-44.yaml:
  - answer_0-0-44_try_0.txt
  - answer_0-0-44_try_1.txt
  - answer_0-0-44_try_2.txt
  cases/eval_0-0-45.yaml:
  - answer_0-0-45_try_0.txt
  - answer_0-0-45_try_1.txt
  - answer_0-0-45_try_2.txt
  cases/eval_0-0-46.yaml:
  - answer_0-0-46_try_0.txt
  - answer_0-0-46_try_1.txt
  - answer_0-0-46_try_2.txt
  cases/eval_0-0-47.yaml:
  - answer_0-0-47_try_0.txt
  - answer_0-0-47_try_1.txt
  - answer_0-0-47_try_2.txt
  cases/eval_0-0-48.yaml:
  - answer_0-0-48_try_0.txt
  - answer_0-0-48_try_1.txt
  - answer_0-0-48_try_2.txt
  cases/eval_0-0-49.yaml:
  - answer_0-0-49_try_0.txt
  - answer_0-0-49_try_1.txt
  - answer_0-0-49_try_2.txt
  cases/eval_0-0-5.yaml:
  - answer_0-0-5_try_0.txt
  - answer_0-0-5_try_1.txt
  - answer_0-0-5_try_2.txt
  cases/eval_0-0-50.yaml:
  - answer_0-0-50_try_0.txt
  - answer_0-0-50_try_1.txt
  - answer_0-0-50_try_2.txt
  cases/eval_0-0-51.yaml:
  - answer_0-0-51_try_0.txt
  - answer_0-0-51_try_1.txt
  - answer_0-0-51_try_2.txt
  cases/eval_0-0-52.yaml:
  - answer_0-0-52_try_0.txt
  - answer_0-0-52_try_1.txt
  - answer_0-0-52_try_2.txt
  cases/eval_0-0-53.yaml:
  - answer_0-0-53_try_0.txt
  - answer_0-0-53_try_1.txt
  - answer_0-0-53_try_2.txt
  cases/eval_0-0-54.yaml:
  - answer_0-0-54_try_0.txt
  - answer_0-0-54_try_1.txt
  - answer_0-0-54_try_2.txt
  cases/eval_0-0-55.yaml:
  - answer_0-0-55_try_0.txt
  - answer_0-0-55_try_1.txt
  - answer_0-0-55_try_2.txt
  cases/eval_0-0-56.yaml:
  - answer_0-0-56_try_0.txt
  - answer_0-0-56_try_1.txt
  - answer_0-0-56_try_2.txt
  cases/eval_0-0-57.yaml:
  - answer_0-0-57_try_0.txt
  - answer_0-0-57_try_1.txt
  - answer_0-0-57_try_2.txt
  cases/eval_0-0-58.yaml:
  - answer_0-0-58_try_0.txt
  - answer_0-0-58_try_1.txt
  - answer_0-0-58_try_2.txt
  cases/eval_0-0-59.yaml:
  - answer_0-0-59_try_0.txt
  - answer_0-0-59_try_1.txt
  - answer_0-0-59_try_2.txt
  cases/eval_0-0-6.yaml:
  - answer_0-0-6_try_0.txt
  - answer_0-0-6_try_1.txt
  - answer_0-0-6_try_2.txt
  cases/eval_0-0-60.yaml:
  - answer_0-0-60_try_0.txt
  - answer_0-0-60_try_1.txt
  - answer_0-0-60_try_2.txt
  cases/eval_0-0-61.yaml:
  - answer_0-0-61_try_0.txt
  - answer_0-0-61_try_1.txt
  - answer_0-0-61_try_2.txt
  cases/eval_0-0-62.yaml:
  - answer_0-0-62_try_0.txt
  - answer_0-0-62_try_1.txt
  - answer_0-0-62_try_2.txt
  cases/eval_0-0-63.yaml:
  - answer_0-0-63_try_0.txt
  - answer_0-0-63_try_1.txt
  - answer_0-0-63_try_2.txt
  cases/eval_0-0-64.yaml:
  - answer_0-0-64_try_0.txt
  - answer_0-0-64_try_1.txt
  - answer_0-0-64_try_2.txt
  cases/eval_0-0-65.yaml:
  - answer_0-0-65_try_0.txt
  - answer_0-0-65_try_1.txt
  - answer_0-0-65_try_2.txt
  cases/eval_0-0-66.yaml:
  - answer_0-0-66_try_0.txt
  - answer_0-0-66_try_1.txt
  - answer_0-0-66_try_2.txt
  cases/eval_0-0-67.yaml:
  - answer_0-0-67_try_0.txt
  - answer_0-0-67_try_1.txt
  - answer_0-0-67_try_2.txt
  cases/eval_0-0-68.yaml:
  - answer_0-0-68_try_0.txt
  - answer_0-0-68_try_1.txt
  - answer_0-0-68_try_2.txt
  cases/eval_0-0-69.yaml:
  - answer_0-0-69_try_0.txt
  - answer_0-0-69_try_1.txt
  - answer_0-0-69_try_2.txt
  cases/eval_0-0-7.yaml:
  - answer_0-0-7_try_0.txt
  - answer_0-0-7_try_1.txt
  - answer_0-0-7_try_2.txt
  cases/eval_0-0-70.yaml:
  - answer_0-0-70_try_0.txt
  - answer_0-0-70_try_1.txt
  - answer_0-0-70_try_2.txt
  cases/eval_0-0-71.yaml:
  - answer_0-0-71_try_0.txt
  - answer_0-0-71_try_1.txt
  - answer_0-0-71_try_2.txt
  cases/eval_0-0-72.yaml:
  - answer_0-0-72_try_0.txt
  - answer_0-0-72_try_1.txt
  - answer_0-0-72_try_2.txt
  cases/eval_0-0-73.yaml:
  - answer_0-0-73_try_0.txt
  - answer_0-0-73_try_1.txt
  - answer_0-0-73_try_2.txt
  cases/eval_0-0-74.yaml:
  - answer_0-0-74_try_0.txt
  - answer_0-0-74_try_1.txt
  - answer_0-0-74_try_2.txt
  cases/eval_0-0-75.yaml:
  - answer_0-0-75_try_0.txt
  - answer_0-0-75_try_1.txt
  - answer_0-0-75_try_2.txt
  cases/eval_0-0-76.yaml:
  - answer_0-0-76_try_0.txt
  - answer_0-0-76_try_1.txt
  - answer_0-0-76_try_2.txt
  cases/eval_0-0-77.yaml:
  - answer_0-0-77_try_0.txt
  - answer_0-0-77_try_1.txt
  - answer_0-0-77_try_2.txt
  cases/eval_0-0-78.yaml:
  - answer_0-0-78_try_0.txt
  - answer_0-0-78_try_1.txt
  - answer_0-0-78_try_2.txt
  cases/eval_0-0-79.yaml:
  - answer_0-0-79_try_0.txt
  - answer_0-0-79_try_1.txt
  - answer_0-0-79_try_2.txt
  cases/eval_0-0-8.yaml:
  - answer_0-0-8_try_0.txt
  - answer_0-0-8_try_1.txt
  - answer_0-0-8_try_2.txt
  cases/eval_0-0-80.yaml:
  - answer_0-0-80_try_0.txt
  - answer_0-0-80_try_1.txt
  - answer_0-0-80_try_2.txt
  cases/eval_0-0-81.yaml:
  - answer_0-0-81_try_0.txt
  - answer_0-0-81_try_1.txt
  - answer_0-0-81_try_2.txt
  cases/eval_0-0-82.yaml:
  - answer_0-0-82_try_0.txt
  - answer_0-0-82_try_1.txt
  - answer_0-0-82_try_2.txt
  cases/eval_0-0-83.yaml:
  - answer_0-0-83_try_0.txt
  - answer_0-0-83_try_1.txt
  - answer_0-0-83_try_2.txt
  cases/eval_0-0-84.yaml:
  - answer_0-0-84_try_0.txt
  - answer_0-0-84_try_1.txt
  - answer_0-0-84_try_2.txt
  cases/eval_0-0-85.yaml:
  - answer_0-0-85_try_0.txt
  - answer_0-0-85_try_1.txt
  - answer_0-0-85_try_2.txt
  cases/eval_0-0-86.yaml:
  - answer_0-0-86_try_0.txt
  - answer_0-0-86_try_1.txt
  - answer_0-0-86_try_2.txt
  cases/eval_0-0-87.yaml:
  - answer_0-0-87_try_0.txt
  - answer_0-0-87_try_1.txt
  - answer_0-0-87_try_2.txt
  cases/eval_0-0-88.yaml:
  - answer_0-0-88_try_0.txt
  - answer_0-0-88_try_1.txt
  - answer_0-0-88_try_2.txt
  cases/eval_0-0-89.yaml:
  - answer_0-0-89_try_0.txt
  - answer_0-0-89_try_1.txt
  - answer_0-0-89_try_2.txt
  cases/eval_0-0-9.yaml:
  - answer_0-0-9_try_0.txt
  - answer_0-0-9_try_1.txt
  - answer_0-0-9_try_2.txt
  cases/eval_0-0-90.yaml:
  - answer_0-0-90_try_0.txt
  - answer_0-0-90_try_1.txt
  - answer_0-0-90_try_2.txt
  cases/eval_0-0-91.yaml:
  - answer_0-0-91_try_0.txt
  - answer_0-0-91_try_1.txt
  - answer_0-0-91_try_2.txt
  cases/eval_0-0-92.yaml:
  - answer_0-0-92_try_0.txt
  - answer_0-0-92_try_1.txt
  - answer_0-0-92_try_2.txt
  cases/eval_0-0-93.yaml:
  - answer_0-0-93_try_0.txt
  - answer_0-0-93_try_1.txt
  - answer_0-0-93_try_2.txt
  cases/eval_0-0-94.yaml:
  - answer_0-0-94_try_0.txt
  - answer_0-0-94_try_1.txt
  - answer_0-0-94_try_2.txt
  cases/eval_0-0-95.yaml:
  - answer_0-0-95_try_0.txt
  - answer_0-0-95_try_1.txt
  - answer_0-0-95_try_2.txt
  cases/eval_0-0-96.yaml:
  - answer_0-0-96_try_0.txt
  - answer_0-0-96_try_1.txt
  - answer_0-0-96_try_2.txt
  cases/eval_0-0-97.yaml:
  - answer_0-0-97_try_0.txt
  - answer_0-0-97_try_1.txt
  - answer_0-0-97_try_2.txt
  cases/eval_0-0-98.yaml:
  - answer_0-0-98_try_0.txt
  - answer_0-0-98_try_1.txt
  - answer_0-0-98_try_2.txt
  cases/eval_0-0-99.yaml:
  - answer_0-0-99_try_0.txt
  - answer_0-0-99_try_1.txt
  - answer_0-0-99_try_2.txt
  cases/eval_0-1-132.yaml:
  - answer_0-1-132_try_0.txt
  - answer_0-1-132_try_1.txt
  - answer_0-1-132_try_2.txt
  cases/eval_0-1-133.yaml:
  - answer_0-1-133_try_0.txt
  - answer_0-1-133_try_1.txt
  - answer_0-1-133_try_2.txt
  cases/eval_0-1-134.yaml:
  - answer_0-1-134_try_0.txt
  - answer_0-1-134_try_1.txt
  - answer_0-1-134_try_2.txt
  cases/eval_0-1-135.yaml:
  - answer_0-1-135_try_0.txt
  - answer_0-1-135_try_1.txt
  - answer_0-1-135_try_2.txt
  cases/eval_0-1-136.yaml:
  - answer_0-1-136_try_0.txt
  - answer_0-1-136_try_1.txt
  - answer_0-1-136_try_2.txt
  cases/eval_0-1-137.yaml:
  - answer_0-1-137_try_0.txt
  - answer_0-1-137_try_1.txt
  - answer_0-1-137_try_2.txt
  cases/eval_0-1-138.yaml:
  - answer_0-1-138_try_0.txt
  - answer_0-1-138_try_1.txt
  - answer_0-1-138_try_2.txt
  cases/eval_0-1-139.yaml:
  - answer_0-1-139_try_0.txt
  - answer_0-1-139_try_1.txt
  - answer_0-1-139_try_2.txt
  cases/eval_0-1-140.yaml:
  - answer_0-1-140_try_0.txt
  - answer_0-1-140_try_1.txt
  - answer_0-1-140_try_2.txt
  cases/eval_0-1-141.yaml:
  - answer_0-1-141_try_0.txt
  - answer_0-1-141_try_1.txt
  - answer_0-1-141_try_2.txt
  cases/eval_0-1-142.yaml:
  - answer_0-1-142_try_0.txt
  - answer_0-1-142_try_1.txt
  - answer_0-1-142_try_2.txt
  cases/eval_0-1-143.yaml:
  - answer_0-1-143_try_0.txt
  - answer_0-1-143_try_1.txt
  - answer_0-1-143_try_2.txt
  cases/eval_0-1-144.yaml:
  - answer_0-1-144_try_0.txt
  - answer_0-1-144_try_1.txt
  - answer_0-1-144_try_2.txt
  cases/eval_0-1-145.yaml:
  - answer_0-1-145_try_0.txt
  - answer_0-1-145_try_1.txt
  - answer_0-1-145_try_2.txt
  cases/eval_0-1-146.yaml:
  - answer_0-1-146_try_0.txt
  - answer_0-1-146_try_1.txt
  - answer_0-1-146_try_2.txt
  cases/eval_0-1-147.yaml:
  - answer_0-1-147_try_0.txt
  - answer_0-1-147_try_1.txt
  - answer_0-1-147_try_2.txt
  cases/eval_0-1-148.yaml:
  - answer_0-1-148_try_0.txt
  - answer_0-1-148_try_1.txt
  - answer_0-1-148_try_2.txt
  cases/eval_0-1-149.yaml:
  - answer_0-1-149_try_0.txt
  - answer_0-1-149_try_1.txt
  - answer_0-1-149_try_2.txt
  cases/eval_0-1-150.yaml:
  - answer_0-1-150_try_0.txt
  - answer_0-1-150_try_1.txt
  - answer_0-1-150_try_2.txt
  cases/eval_0-1-151.yaml:
  - answer_0-1-151_try_0.txt
  - answer_0-1-151_try_1.txt
  - answer_0-1-151_try_2.txt
  cases/eval_0-2-152.yaml:
  - answer_0-2-152_try_0.txt
  - answer_0-2-152_try_1.txt
  - answer_0-2-152_try_2.txt
  cases/eval_0-2-153.yaml:
  - answer_0-2-153_try_0.txt
  - answer_0-2-153_try_1.txt
  - answer_0-2-153_try_2.txt
  cases/eval_0-2-154.yaml:
  - answer_0-2-154_try_0.txt
  - answer_0-2-154_try_1.txt
  - answer_0-2-154_try_2.txt
  cases/eval_0-2-155.yaml:
  - answer_0-2-155_try_0.txt
  - answer_0-2-155_try_1.txt
  - answer_0-2-155_try_2.txt
  cases/eval_0-2-156.yaml:
  - answer_0-2-156_try_0.txt
  - answer_0-2-156_try_1.txt
  - answer_0-2-156_try_2.txt
  cases/eval_0-2-157.yaml:
  - answer_0-2-157_try_0.txt
  - answer_0-2-157_try_1.txt
  - answer_0-2-157_try_2.txt
  cases/eval_0-2-158.yaml:
  - answer_0-2-158_try_0.txt
  - answer_0-2-158_try_1.txt
  - answer_0-2-158_try_2.txt
  cases/eval_0-2-159.yaml:
  - answer_0-2-159_try_0.txt
  - answer_0-2-159_try_1.txt
  - answer_0-2-159_try_2.txt
  cases/eval_0-2-160.yaml:
  - answer_0-2-160_try_0.txt
  - answer_0-2-160_try_1.txt
  - answer_0-2-160_try_2.txt
  cases/eval_0-2-161.yaml:
  - answer_0-2-161_try_0.txt
  - answer_0-2-161_try_1.txt
  - answer_0-2-161_try_2.txt
  cases/eval_0-2-162.yaml:
  - answer_0-2-162_try_0.txt
  - answer_0-2-162_try_1.txt
  - answer_0-2-162_try_2.txt
  cases/eval_0-2-163.yaml:
  - answer_0-2-163_try_0.txt
  - answer_0-2-163_try_1.txt
  - answer_0-2-163_try_2.txt
  cases/eval_0-2-164.yaml:
  - answer_0-2-164_try_0.txt
  - answer_0-2-164_try_1.txt
  - answer_0-2-164_try_2.txt
  cases/eval_0-2-165.yaml:
  - answer_0-2-165_try_0.txt
  - answer_0-2-165_try_1.txt
  - answer_0-2-165_try_2.txt
  cases/eval_0-2-166.yaml:
  - answer_0-2-166_try_0.txt
  - answer_0-2-166_try_1.txt
  - answer_0-2-166_try_2.txt
  cases/eval_0-2-167.yaml:
  - answer_0-2-167_try_0.txt
  - answer_0-2-167_try_1.txt
  - answer_0-2-167_try_2.txt
  cases/eval_0-2-168.yaml:
  - answer_0-2-168_try_0.txt
  - answer_0-2-168_try_1.txt
  - answer_0-2-168_try_2.txt
  cases/eval_0-2-169.yaml:
  - answer_0-2-169_try_0.txt
  - answer_0-2-169_try_1.txt
  - answer_0-2-169_try_2.txt
  cases/eval_0-2-170.yaml:
  - answer_0-2-170_try_0.txt
  - answer_0-2-170_try_1.txt
  - answer_0-2-170_try_2.txt
  cases/eval_0-2-171.yaml:
  - answer_0-2-171_try_0.txt
  - answer_0-2-171_try_1.txt
  - answer_0-2-171_try_2.txt
max_tokens: null
model_name: gpt-4
qa_system_prompt: You are a professional assistant for programmers.
sample_n: 3
system_prompt: You are a professional assistant for programmers.
temp: 0.2
top_p: 0.9
